Add HandwritingOCR SDK for windows platform
mike-int/Cognitive-Vision-Windows pull request #1
Opened 2017-03-07 01:41 UTC by Sinkee

Add HandwritingOCR SDK for windows platform

2017-03-09 06:35 UTC, qiwjin commented on ClientLibrary/Contract/HandwritingOCRLine.cs
> +    public class HandwritingOCRLine
double check the class name with xj

2017-03-09 06:42 UTC, qiwjin requested changes

2017-03-09 06:42 UTC, qiwjin commented on ClientLibrary/Contract/HandwritingOCRLine.cs
> +        public int[] BoundingBox { get; set; }
use int[] to represent box?

2017-03-09 06:42 UTC, qiwjin commented on ClientLibrary/Contract/HandwritingOCROperation.cs
> +    public class HandwritingOCROperation
name?

2017-03-09 06:42 UTC, qiwjin commented on ClientLibrary/Contract/HandwritingOCRWord.cs
> +        public int[] BoundingBox { get; set; }
same as above

2017-03-09 06:42 UTC, qiwjin commented on Sample-WPF/HandwritingOCRPage.xaml.cs
> +        private async Task<HandwritingOCROperationResult> Recognize(Func<VisionServiceClient, Task<HandwritingOCROperation>> Func)
change the name to RecognizeAsync?

2017-03-09 06:42 UTC, qiwjin commented on Sample-WPF/HandwritingOCRPage.xaml.cs
> +                    result = await VisionServiceClient.GetHandwritingOCROperationResultAsync(operation);
add some code to demo how to use the result

2017-03-09 07:34 UTC, hippogr requested changes

2017-03-09 07:34 UTC, hippogr commented on ClientLibrary/VisionServiceClient.cs
> +            //request.Headers[HttpRequestHeader.Authorization] = "Basic ZTkwNTE2ZmQ4NThlNDVjMmFhNDMzMjRlZjBlOThlN2E=";
why remove this?

2017-03-09 07:34 UTC, hippogr commented on ClientLibrary/VisionServiceClient.cs
> +
please add some comments to explain why we need do this

2017-03-09 07:34 UTC, hippogr commented on Sample-WPF/HandwritingOCRPage.xaml.cs
> +            _status.Text = "HandwritingOCR Done";
handwriting recognition finished.

2017-03-09 07:56 UTC, Sinkee commented on Sample-WPF/HandwritingOCRPage.xaml.cs
> +                    result = await VisionServiceClient.GetHandwritingOCROperationResultAsync(operation);
We have a log result method, which is used to demo how to use the result.

2017-03-10 02:55 UTC, mike-int commented on ClientLibrary/Contract/HandwritingOCRLine.cs
> +    public class HandwritingOCRLine
Sync with xj and udpate.

2017-03-10 02:56 UTC, mike-int commented on ClientLibrary/Contract/HandwritingOCRLine.cs
> +        public int[] BoundingBox { get; set; }
keep the array and add a polygon to represent the line boundary.

2017-03-10 02:56 UTC, mike-int commented on ClientLibrary/Contract/HandwritingOCROperation.cs
> +    public class HandwritingOCROperation
update

2017-03-10 02:56 UTC, mike-int commented on ClientLibrary/Contract/HandwritingOCRWord.cs
> +        public int[] BoundingBox { get; set; }
keep the array and add a polygon to represent the word boundary.

2017-03-10 02:56 UTC, mike-int commented on Sample-WPF/HandwritingOCRPage.xaml.cs
> +        private async Task<HandwritingOCROperationResult> Recognize(Func<VisionServiceClient, Task<HandwritingOCROperation>> Func)
update

2017-03-10 02:57 UTC, mike-int commented on ClientLibrary/VisionServiceClient.cs
> +            //request.Headers[HttpRequestHeader.Authorization] = "Basic ZTkwNTE2ZmQ4NThlNDVjMmFhNDMzMjRlZjBlOThlN2E=";
recover

2017-03-10 02:57 UTC, mike-int commented on ClientLibrary/VisionServiceClient.cs
> +
added.

2017-03-10 02:57 UTC, mike-int commented on Sample-WPF/HandwritingOCRPage.xaml.cs
> +            _status.Text = "HandwritingOCR Done";
update

2017-03-10 06:33 UTC, qiwjin approved these changes

2017-03-13 03:40 UTC, merged